# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source
    
COPY . .
RUN dotnet restore "./Koerber.API/Koerber.API.csproj" --disable-parallel
RUN dotnet publish "./Koerber.API/Koerber.API.csproj" -c release -o /app --no-restore
        
# Serve Stage
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app ./

ENV LOAD_DATA = "NO"

EXPOSE 5000

ENTRYPOINT ["dotnet", "Koerber.API.dll"]